import type { ChurchNews } from "@/entities/admin/NewsManager";

export const categoryOptions: { value: string; label: string }[] = [
  { value: "ministry", label: "사역" },
  { value: "event", label: "행사" },
  { value: "mission", label: "선교" },
  { value: "education", label: "교육" },
  { value: "fellowship", label: "교제" },
  { value: "others", label: "기타" },
];

export const churchNews: ChurchNews[] = [
  {
    id: 1,
    title: "창립 기념 행사",
    content: "교회 창립 기념 행사가 열립니다. 많은 참여 부탁드립니다.",
    summary: "창립 기념 행사 안내",
    category: "행사",
    status: "published",
    imageUrl: "https://example.com/image1.jpg",
    tags: ["창립", "기념", "행사"],
    author: "홍길동",
    publishedAt: "2025-08-01T14:00:00Z",
    createdAt: "2025-07-30T14:00:00Z",
    updatedAt: "2025-08-01T14:00:00Z",
  },
  {
    id: 2,
    title: "여름 성경학교",
    content: "다음 주부터 여름 성경학교가 시작됩니다.",
    category: "교육",
    status: "draft",
    tags: ["성경학교", "교육"],
    author: "이영희",
    createdAt: "2025-07-20T09:00:00Z",
    updatedAt: "2025-08-02T14:22:00Z",
  },
  {
    id: 3,
    title: "선교 보고",
    content: "지난 한 달 동안의 해외 선교 활동을 보고합니다.",
    summary: "선교 활동 결과 보고",
    category: "선교",
    status: "published",
    imageUrl: "https://example.com/image2.jpg",
    tags: ["선교", "보고"],
    author: "김철수",
    publishedAt: "2025-08-05T17:00:00Z",
    createdAt: "2025-06-15T17:00:00Z",
    updatedAt: "2025-08-01T17:00:00Z",
  },
  {
    id: 4,
    title: "추수감사절 행사 안내",
    content: "추수감사절 행사가 예정되어 있습니다. 많은 참석 부탁드립니다.",
    summary: "추수감사절 행사 일정",
    category: "행사",
    status: "draft",
    imageUrl: "https://example.com/image3.jpg",
    tags: ["추수감사절", "행사"],
    author: "박민수",
    createdAt: "2025-07-25T12:00:00Z",
    updatedAt: "2025-07-30T12:30:00Z",
  },
  {
    id: 5,
    title: "지역 사회 봉사 활동",
    content: "이번 주말에 진행될 봉사 활동에 많은 참여 바랍니다.",
    summary: "봉사 활동 안내",
    category: "봉사",
    status: "published",
    imageUrl: "https://example.com/image4.jpg",
    tags: ["봉사", "사회"],
    author: "최지희",
    publishedAt: "2025-08-10T09:30:00Z",
    createdAt: "2025-08-01T09:00:00Z",
    updatedAt: "2025-08-05T09:30:00Z",
  },
];
